[admin]
see_own_notes   = true
deadmin_on_join = true

[discord]
# rich_main_icon_id = "einstein-engines"

[events]
ramping_average_end_time = 180.0
ramping_average_chaos    = 2

[game]
hostname           = "Vulpstation"
desc               = "A successor of floofstation. Currently in the set-up phase."
soft_max_players   = 30
lobbyenabled       = true
lobbyduration      = 180

[hub]
tags = "lang:en-US,region:am_n_e,rp:med"
hub_urls = "https://hub.spacestation14.com/"

[ic]
flavor_text = true

[infolinks]
discord    = "https://discord.gg/M7sRnrNwPp"
github     = "https://github.com/Vulpstation/Vulpstation/"
#website    = "https://simplestation.org/"
bug_report = "https://github.com/Vulpstation/Vulpstation/issues/new/choose"

[net]
max_connections = 1024
tickrate = 30

[netres]
limit = 10.0

[build]
#! PLEASE set this for your fork
fork_id = "Vulpstation"

[server]
rules_file   = "DefaultRuleset"

[ooc]
enable_during_round = true

[vote]
restart_required_ratio = 0.65
preset_enabled = true
map_enabled = true

#[worldgen]
#enabled = true
